### ISSUE TITLE
fptf 2.0.0 checklist

### ISSUE THREAD

**Issue by juliuste** [public-transport/friendly-public-transport-format#37]
Things we need to work on for fptf `2.0.0`:

- [ ] add a code of conduct (?) #36
- [ ] decide on / implement `stopover` type #35
- [ ] decide how to handle realtime/scheduled time information and decide on the usage of `schedule` / `line` in journeys #5 #33
- [ ] add the `canceled` attribute #27
- [ ] decide on wether to "forbid" redundant origin/destination information in journeys #34 

This issue's intention is not to rush publishing the next version, it should just provide a neat checklist for what we still have to work on.

**Comment by derhuerst** [comment]
- [ ] make `journey.price`/`leg.price` an array of prices

**Comment by juliuste** [comment]
I like the idea of adding multiple prices to FPTF `journey`s, however I find it quite useful to have the current way of expressing sth. like *this is the price you pay in the default class without any reductions* and I feel like we should keep some form of expressing this. For example, one price in prices should have the attribute `default: true`, or something similar.

**Comment by derhuerst** [comment]
Not sure what the "default class" would be. Imagine a ferry with "car", "truck", "bicycle" and "without any" tickets; What would be the default?

Also there are more things than 1st/2nd/whatever class, e.g.

- daily ticket vs single ride vs 10 rides
- sparpreis vs regular price
- tickets with better service

I don't see why we wouldn't have a `default` flag for those cases with a *default* price.

**Comment by matkoniecz** [comment]
> daily ticket vs single ride vs 10 rides

In this case "single ride" is clearly a default value.

> tickets with better service

Standard service would be a default price, "better service" sounds like "1st class"

> Not sure what the "default class" would be. Imagine a ferry with "car", "truck", "bicycle" and "without any" tickets; What would be the default?

This is tricky, I imagine that it depends on situation, sometimes one case dominates (for car centric ferry where 99% people travel with car answer is obvious, for passenger oriented ferry with single place for occasional car answer is also obvious). But at least sometimes there is no obvious default - maybe allow "null" for such cases?

> sparpreis vs regular price

sparpreis is not an English word, Google translate gives "saving award" what is not clear for me (though it seems obvious that default is "regular price")

**Comment by matkoniecz** [comment]
In general - in most situations there is a clear, standard price (without upgrades, special services, discounts etc) and it would be nice to have way to specify it.

**Comment by derhuerst** [comment]
>> tickets with better service
>
> Standard service would be a default price, "better service" sounds like "1st class"

For a flight, would the default price include or exclude baggage?

> But at least sometimes there is no obvious default - maybe allow "null" for such cases?

Agree! I'd definitely make the `price.default`/`price.isDefault` flag optional.

> In general - in most situations there is a clear, standard price (without upgrades, special services, discounts etc) and it would be nice to have way to specify it.

I don't disagree! I'm only against having `journey.price` (which makes it awkward to expose multiple prices).
